-- Record the cached half of a prompt, so the ledger can price it as one.
--
-- `prompt_tokens` has always held the WHOLE billed input, and `estimateCostUsd`
-- priced all of it at the input rate — the only rate a row carried enough
-- information to apply. Every provider Gnomon runs on serves a repeated prefix
-- from cache at a fraction of that rate (TensorX: $0.05/1M against $0.20/1M
-- input on qwen3.8-flash-next), and a chat turn replays its whole history, so
-- the cached fraction is most of the call. Measured on the live session log:
-- 85.5% of chat input was a cache read, which made the ledger's `ask` estimate
-- 2.79x the real input cost (the cache tier is a quarter of the input tier).
--
-- This column is a SUBSET of `prompt_tokens`, never an addition to it. Rows
-- written before it exists stay NULL and keep the old, high estimate rather
-- than being back-filled with a guess.
ALTER TABLE `llm_audit` ADD `cache_read_tokens` integer;
