-- H1: what a model read in the owner's own answer, filed BESIDE it.
--
-- JSON array of `{entityKind, canonicalName, predicate, object, confidence}` —
-- `AskProposal` in @sundial/kernel. It is not a fact and it never becomes one on
-- its own: the owner pressing Keep on the card is what writes, through
-- `/gnomon/api/assert`, exactly as `transcript-clean` keeps the raw capture the
-- truth until they press Accept.
--
-- Three states, and the card needs all three: NULL is "not looked at yet", `[]`
-- is "looked at, nothing there", and a non-empty array is a filled-in form. No
-- backfill here on purpose — `askHarvestBackfill` drains the 49 existing
-- answers one an hour, so the NULLs are what tells it where it got to.
ALTER TABLE `owner_asks` ADD `proposals` text;
